app/extensions/models.py
from app.extensions.database import db

#class User(db.Model):
 #   id = db.Column(db.Integer, primary_key=True)
 #  name = db.Column(db.String(128))

class CRUDMixin():
    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

app/orders/models.py
from app.extensions.database import db, CRUDMixin
from datetime import datetime
from flask_login import UserMixin


class Works(db.Model, CRUDMixin):
  __tablename__ = 'works'
  id = db.Column(db.Integer, primary_key=True, unique=True)
  slug = db.Column(db.String(80))
  name = db.Column(db.String(80))
  description = db.Column(db.String(200))
  price = db.Column(db.Numeric(10, 2))
  user_id = db.Column(db.Integer, db.ForeignKey('user.id', name='fk_user_id'))


class User(db.Model, UserMixin):
  id = db.Column(db.Integer, primary_key=True, unique=True)
  email = db.Column(db.String(150), unique=True)
  username = db.Column(db.String(150))
  password = db.Column(db.String(150))
  works = db.relationship('Works', backref=db.backref('user', lazy=True))


class Order(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
  address = db.relationship('Address', backref='order', uselist=False, lazy=True)

class Address(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(80))
  street = db.Column(db.String(80))
  city = db.Column(db.String(80))
  state = db.Column(db.String(80))
  zip = db.Column(db.String(80))
  country = db.Column(db.String(80))
  order_id = db.Column(db.Integer, db.ForeignKey('order.id'))

app/app.py
from flask import Flask
from flask_login import LoginManager
from app.orders.models import User
from app.extensions.database import migrate
from app.extensions.database import db
from app.orders.routes import orders_blueprint

login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config')

    app.secret_key = app.config['SECRET_KEY']

    # Initialize LoginManager
    login_manager.init_app(app)
    login_manager.login_view = 'orders.register'

    register_extensions(app)
    register_blueprints(app)

    return app

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

def register_blueprints(app: Flask):
    app.register_blueprint(orders_blueprint)

def register_extensions(app: Flask):
    from app.extensions.database import db
    from flask_migrate import Migrate

    db.init_app(app)
    migrate = Migrate(app, db, compare_type=True)
    migrate.init_app(app, db, compare_type=True)

app/cookies/__init__.py
from flask import Blueprint

cookies_blueprint = Blueprint('cookies', __name__)

def register_blueprints(app):
    app.register_blueprint(cookies_blueprint)

app/extensions/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'

db = SQLAlchemy(app)
migrate = Migrate(app, db)

app/orders/__init__.py
from flask import Blueprint

orders_blueprint = Blueprint('orders', __name__)

from . import routes

def register_blueprints(app):
    app.register_blueprint(orders_blueprint)

app/orders/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort
from app.extensions.database import db
from app.orders.models import Order, Address, Works, User
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
from flask_login import login_user, login_required, logout_user, current_user

orders_blueprint = Blueprint('orders', __name__)

def register_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_authenticated:
            return f(*args, **kwargs)
        else:
            flash('You need to be registered to access this page.', category='error')
            return redirect(url_for('orders.login'))
    return decorated_function

@orders_blueprint.route('/')
def homework():
    return render_template('homework.html')

@orders_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 3:
            flash('Email must be greater than 3 characters', category='error')
        elif len(username) < 1:
            flash('First name must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password much be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('orders.about'))

    return render_template('register.html')

@orders_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        username = request.form.get('username')
        user = User.query.filter_by(email=email).first()
        if user:
            if user.username != username:
                flash('Incorrect user name, try again', category='error')
            elif check_password_hash(user.password, password):
                flash('Logged in successfully', category='success')
                login_user(user, remember=True)
                return redirect(url_for('orders.about'))
            else:
                flash('Incorrect password, try again', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template('login.html')


@orders_blueprint.route('/about', methods=['GET', 'POST'])
@register_required
def about():
    if request.method == 'POST':
        name = request.form['title']
        description = request.form['description']
        price = request.form['price']
        from time import time
        slug = f"{name}-{int(time())}"
        new_work = Works(slug=slug, name=name, description=description, price=price)
        new_work.save()
    works = Works.query.all()
    return render_template('About.html', works=works)


@orders_blueprint.route('/all_works')
def all_works():
    all_works = Works.query.all()
    return render_template('Works.html', works=all_works)

@orders_blueprint.route('/works/<slug>', methods=['GET', 'POST'])
def works(slug):
    works = Works.query.filter_by(slug=slug).first()
    if request.method == 'POST':
        if 'Update' in request.form:
            works.name = request.form['title']
            works.description = request.form['description']
            works.price = request.form['price']
            db.session.commit()
            flash('Work updated successfully', category='success')
            return redirect(url_for('orders.about'))

        elif 'Delete' in request.form:
            db.session.delete(works)
            db.session.commit()
            flash('Work deleted successfully', category='success')
            return redirect(url_for('orders.about'))

    return render_template('show.html', works=works)

app/templates/About.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}


{% block body %}

<div class="about_page">

<div class="About_container">
    <h1>About</h1>
    <p class="body_text">
        Vivamus fermentum semper porta. Nunc diam velit, adipscing ut
        tristique vitae sagittis vel odio. Maecenas convallis ullamcorper
        ultricied. Curabitur ornare, ligula semper consectetur sagittis, nisi
        diam iaculis velit, is fringille sem nunc vet mi.
    </p>
</div>

<div class = "List_of_Works">
    <div class="list_works">
    <h1>List of Works</h1>
    <ul>
        {% for works in works %}
        <li class="work_item">
            <form action="{{ url_for('orders.works', slug=works.slug) }}" method="POST">
                {{works.name}}
                <p>{{works.description}}</p>
                <p>price: {{works.price}}$</p>
                <button type="submit">Change</button>
            </form>
        </li>
        {% endfor %}
    </ul>
    </div>

    <div class="submit_your_works">
    <h1>Submit Your Works</h1>
    <form action="/about", method="POST">
        <label for="title">Title</label><br>
        <input type="text" id="title" name="title" required><br><br>

        <label for="description">Description:</label>
        <textarea id="description" name="description" rows="4" cols="50" required></textarea><br><br>

        <label for="price">price:</label>
        <input type="number" id="price" name="price" required><br><br>

        <button type="submit">Submit</button>
    </form>
    </div>
</div>
</div>
{% endblock %}

app/templates/Works.html
{% extends 'base.html' %}

{% block title %}Works{% endblock %}


{% block body %}


<div class="gallery">
    <div class="gallery_item gallery_item_1">
        <a href="#" class="gallery_link">
            <img src="{{ url_for('static', filename='css/anxiety.png') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Screaming Face </span>
                </div>
        </a>
    </div>

    <div class="gallery_item gallery_item_2">
        <a href="#" class="gallery_link">
             <img src="{{ url_for('static', filename='css/sadness.png') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Russian sadness</span>
                </div>
        </a>
    </div>
    <div class="gallery_item gallery_item_3">
        <a href="#" class="gallery_link">
            <img src="{{ url_for('static', filename='css/mind.jpg') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Trapped inside my mind</span>
                </div>
        </a>
    </div>
    <div class="gallery_item gallery_item_4">
        <a href="#" class="gallery_link">
            <img src="{{ url_for('static', filename='css/loving.png') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Loving</span>
                </div>
        </a>
    </div>
    <div class="gallery_item gallery_item_5">
        <a href="#" class="gallery_link">
            <img src="{{ url_for('static', filename='css/sadness.png') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Russian sadness</span>
                </div>
        </a>
    </div>

    <div class="gallery_item gallery_item_6">
        <a href="#" class="gallery_link">
            <img src="{{ url_for('static', filename='css/mind.jpg') }}" class="gallery_image" />
                <div class="gallery_overlay">
                    <span>Trapped inside my mind</span>
                </div>
        </a>
    </div>

</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/my.css') }}">
    <script defer src="{{ url_for('static', filename='javascript/index.js') }}"></script>
  {% endblock %}
</head>
<header>
<nav>
        <div class="menu">
            <div class="logo">
                <a href="/">Auslanderina</a>
            </div>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/all_works">Works</a></li>
                <li><a href="/register">Register</a></li>
                <li><a href="/login">Login</a></li>
            </ul>
        </div>
    </nav>

<div class="flash-container">
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% else %}
        <div class="alert alert-success alert-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
  {% endwith %}
</div>

  {% block header %} {% endblock %}
</header>
<body>
  {% block body %}{% endblock %}
</body>
</html>

app/templates/homework.html
{% extends 'base.html' %}

{% block title %}My Blog{% endblock %}


{% block header %}
    <div class="IMG_3314"></div>
    <div class="center">
        <div class="title">AUSLANDERINA</div>
        <div class="sub_title">Explorations of life</div>
    </div>
{% endblock %}

{% block body %}
<ul>
    {% for work in works %}
        <li>
          {% if work.price == 0.25 %}
          <s>{{ work.name }}</s>
          {% else %}
          <a href="/works/ {{ work.slug}}"> {{ work.name}}</a>
          {% endif %}
        </li>
    {% endfor %}
</ul>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block head %}
  {{ super() }}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
{% endblock %}

{% block body %}
  <div class="container">
      <div class="login_register_form">
      <form id="form" action="{{ url_for('orders.login') }}" method="post">
          <h1>Login</h1>
          <div class="input-control">
              <label for="username">Username</label>
              <input id="username" name="username" type="text">
              <div class="error"></div>
          </div>
          <div class="input-control">
              <label for="email">Email</label>
              <input id="email" name="email" type="text">
              <div class="error"></div>
          </div>
          <div class="input-control">
              <label for="password">Password</label>
              <input id="password" name="password" type="password">
              <div class="error"></div>
          </div>
          <button type="submit">Log In</button>
      </form>
      </div>
      <div class="register-link">
          <p>Don't have an account? <a href="/register">Register here</a>.</p>
      </div>
  </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block head %}
  {{ super() }}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
{% endblock %}

{% block body %}
  <div class="container">
      <div class="login_register_form">
      <form id="form"  action="{{ url_for('orders.register') }}" method="POST">
          <h1>Registration</h1>
          <div class="input-control">
              <label for="username">Username</label>
              <input id="username" name="username" type="text">
              <div class="error"></div>
          </div>
          <div class="input-control">
              <label for="email">Email</label>
              <input id="email" name="email" type="text">
              <div class="error"></div>
          </div>
          <div class="input-control">
              <label for="password1">Password</label>
              <input id="password1" name="password1" type="password">
              <div class="error"></div>
          </div>
          <div class="input-control">
              <label for="password2">Password again</label>
              <input id="password2" name="password2" type="password">
              <div class="error"></div>
          </div>
          <button type="submit">Sign Up</button>
      </form>
      </div>
  </div>
{% endblock %}

app/templates/show.html
{% extends 'base.html' %}

{% block title %}Edit Work{% endblock %}

{% block body %}
    <div class="edit_work">
    <h1>Edit Work</h1>
    <form action="{{ url_for('orders.works', slug=works.slug) }}" method="POST">
        <label for="title">Title</label><br>
        <input type="text" id="title" name="title" value="{{ works.name }}" required><br><br>

        <label for="description">Description:</label>
        <textarea id="description" name="description" rows="4" cols="50" required>{{ works.description }}</textarea><br><br>

        <label for="price">Price:</label>
        <input type="number" id="price" name="price" value="{{ works.price }}" required><br><br>

        <button type="submit", name="Update">Update</button>
        <button type="submit", name="Delete">Delete</button>
    </form>
    </div>
{% endblock %}